service: pipeline-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, env:STAGE}
  region: ${opt:region, env:REGION}
  deploymentBucket: "serverless-deployments-${self:provider.region}-${opt:account, env:ACCOUNT}"
  variableSyntax: '\${((env|self|opt|file|cf|s3|ssm)[:\(][ :a-zA-Z0-9._,\-\/\(\)]*?)}'

functions:
  hello:
    handler: handler.hello
